version: '3.1'

services:
  be-postgres:
    container_name: be-postgres
    image: postgres:13-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
      TZ: 'GMT+3'
      PGTZ: 'GMT+3'
    volumes:
      - be_postgres_data:/var/lib/postgresql/data

volumes:
  be_postgres_data: